jobs/ops_job-generator_kernel.yaml, scripts/kernel/job-generator-kernel.sh, scripts/kernel/job-trigger-kernel.groovy
@mjeanson  could you review this?
See this jobs log https://ci.lttng.org/job/job_generator_kernel/.
Will need to be regenerated once it's merged since for now it use my repo for lttng-ci.
Thanks
=> Job generator for kernel and lttng-modules

etc/jenkins_jobs.ini-sample, jobs/ops_job-generator_kernel.yaml, scripts/kernel/job-generator-kernel.sh
Since the rc are deleted based on the previous version file it's imperative to
keep it from time to time to ensure deletion of unwanted rc jobs.
@mjeanson mind looking at this ?
=> Run generator_kernel on master and keep the version state

jobs/lttng-scope.yml
All plugins have been moved to the top-level, the "releng/" part is no
longer needed.
Signed-off-by: Alexandre Montplaisir <alexmonthy@efficios.com>
=> jjb: Update paths in lttng-scope job

jobs/lttng-baremetal-tests.yaml
Replace stable-2.8 tests by stable-2.10.
=> Test only supported LTTng versions

lava/baremetal-tests/failing-close.yml, lava/baremetal-tests/failing-ioctl.yml, lava/baremetal-tests/failing-open-efault.yml, lava/baremetal-tests/failing-open-enoent.yml, lava/baremetal-tests/lttng-test-filter.yml, lava/baremetal-tests/raw-syscall-getpid.yml, lava/baremetal-tests/success-dup-close.yml
The clone target directory must not exist.
=> Fix lava benchmark git clone path

jobs/babeltrace.yaml, jobs/lttng-tools.yaml
Publisher anchors do not behave as expected. They overwrite each other
instead of merging their array values (irc notification, tap parsing, etc.)
Yaml does not support array merging via anchor [1]. Duplicate the
"default" value into the more defined publisher anchor.
[1] https://stackoverflow.com/questions/24090177/how-to-merge-yaml-arrays/30770740#30770740
=> Fix: YAML does not support object merging or array merging for anchor

scripts/latency-tracker/master-rt.groovy, scripts/latency-tracker/master.groovy, scripts/lttng-modules/master-rt.groovy, scripts/lttng-modules/master.groovy
getExecutor().interrupt(FAILURE) flag the build as aborted event if the final status is FAILURE.
This influence triggers such as email.
07:28:26 lttng-modules_VERSION_param-build #334163 (v4.12.14) completed with status SUCCESS
07:28:26 lttng-modules_VERSION_param-build #334160 (v4.15-rc3) completed with status FAILURE
...
07:28:26 lttng-modules_VERSION_param-build #334220 (v2.6.37.6) completed with status SUCCESS
07:28:26 Build was aborted
Marked as "aborted".
07:28:26 Started calculate disk usage of build
07:28:26 Finished Calculation of disk usage of build in 0 seconds
07:28:26 Started calculate disk usage of workspace
07:28:26 Finished Calculation of disk usage of workspace in 0 seconds
07:28:26 [WS-CLEANUP] Deleting project workspace...[WS-CLEANUP] done
07:28:26 No emails were …
=> Use setResult instead of getExecutor().interrupt to set FAILURE

README.md, tox.ini
=> Use github.com/lttng/jenkins-job-builder instead of a personal repo

scripts/system-tests/lava-submit.py
We now use the debugfs interface to enable kprobe events, so we don't
need to setup an LTTng env anymore.
=> jjb: lava: kprobe-fuzzing: Don't setup lttng env

lava/system-tests/kprobe-fuzzing-generate-data.yml, lava/system-tests/kprobe-fuzzing-tests.yml, scripts/system-tests/lava-submit.py, scripts/system-tests/run-kprobe-fuzzing.py
With the current configuration, the fuzzing is done in a single Lava
testcase. If the kernel crashes during the testcase, the Lava slave will
be rebooted once the timeout expires(currently 2 hours). If the testcase
crashes at the beginning of the testcase, the job still has to wait for
the timeout to expire. That causes a lot of wasted time.
We overcome this by split the fuzzing into multiple smaller testcases
all with a smaller timeout and a specific range of instrumentation
points to test. This has the benefits of increasing our testing coverage
and resource efficiency.
This PR also add the missing deactivation of the events after each iterations and add a seed parameter to the fuzzing data generation script.
=> jjb: lava: kprobe-fuzzing: Split testcase into multiple independent ones

lava/system-tests/kprobe-fuzzing-tests.yml
The fuzzing is targeting the kernel so there is no value to gather
userspace coredumps.
=> jjb: lava: kprobe-fuzzing: Remove coredump recovery step

scripts/system-tests/run-kprobe-generate-instr-points.py
Probing ftrace functions like ftrace_ops_assist_func and some other
function can cause crash and it won't be fixed in the foreseeable future.
=> jjb: lava: kprobe-fuzzing: Don't fuzz ftrace functions

scripts/system-tests/system-trigger.groovy
Since the kprobe fuzzing has in important random aspect, we can run it
daily to increase the instrumentation coverage.
=> jjb: lava: Run fuzzing job daily regardless of code changes

jobs/system-tests.yaml
Because of DNS resolving downtime during backups on weekends we need to
make sure that the long running Lava jobs are scheduled early in the day
so they have time to complete before we pass midnight.
It was causing problems when a lot of Lava jobs were scheduled late
Friday afternoon and some jobs ended up being queued until Saturday
morning when DNS resolving was down.
=> jjb: lava: Schedule trigger jobs on early morning on week days

jobs/lttng-tools.yaml, scripts/lttng-tools/build.sh
The likely stuck timeout policy is used since those jobs take a long time. We should be able to change it later to a static time value when multiple run of the jobs converge toward a certain duration. The likely policy is mostly the following [1]:
```
if (eta)
maxTime = 10 * eta
else
maxTime = 24 hours
```
[1] https://github.com/jenkinsci/build-timeout-plugin/blob/246216187fd2d55cc5be301abdbe3468a5422871/src/main/java/hudson/plugins/build_timeout/impl/LikelyStuckTimeOutStrategy.java#L20
Create new jobs since performing long regression testing on
multi-axial matrix would simply take to much time.
=> Add long regression testing for lttng-tools

jobs/lttng-tools.yaml, scripts/lttng-tools/build.sh, scripts/lttng-tools/clean_processes_coredump.sh, scripts/lttng-tools/hang_processes.sh
Tests often fail because of "dangling" lttng processes left on CI slaves. I am not sure what leaks them (either failing tests or cancelled jobs), but they are a very frequent cause of build failures.
The code is this diff is taken from lttng-tools' `warn_processes.sh`.
We could also clean-up at the end of the job, but I am not sure how to get Jenkins to run a "clean-up" when a job is cancelled (e.g. manually or after a time-out).
=> Kill dangling test processes before running tests

scripts/lttng-tools/hang_processes.sh
We use the WORKSPACE variable, which is normally set by Jenkins.
To allow testing the script by hand, set it manually to the current
working directory if it is not defined.
Signed-off-by: Simon Marchi <simon.marchi@efficios.com>
=> hang_processes.sh: Set WORKSPACE variable when running outside of Jenkins

scripts/common/scan-build.sh
These options prevent a lot of false positive reports, mainly in cases
where variable are set only used in assertions or some log levels.
=> jjb: add babeltrace scan-build configure options

scripts/system-tests/lava2-submit.py
Since PyYAML version 5.2 `load()` errors out when parsing such field:
!!python/object/apply:collections.OrderedDict [...]
This is done to prevent vulnerabilities exploitable using the
`object/apply` construct. See this Github issue [1]:
I believe the real bug is that Lava produce a yaml file with such a
construct. I believe it's not on purpose because we can see a commit [2]
preventing the use of `object/apply` for another type.
For now, use `unsafe_load()` until lava does not produce `object/apply`
contructs.
[1] https://github.com/yaml/pyyaml/issues/364
[2] https://github.com/Linaro/lava/commit/14b347c51efb89e8d6c64d9aa74fb4190f03227c
=> jjb: system-tests: use `yaml.unsafe_unload()` method

scripts/system-tests/lava2-submit.py
In the vm_tests_* lava jobs, there are currently 2 sub-tests that we
care about: "1_kernel-tests" and "2_destructive-tests".
At the moment, we print from the first '<LAVA_SIGNAL_STARTTC run-tests>'
to the first '<LAVA_SIGNAL_ENDTC run-tests>' we encounter.
This is wrong because there are 2 sub-tests, we are currently only print
the result of the first one.
To fix this,  don't break from the loop and keep on reading the file in
case there are other test results.
=> jjb: system-tests: print all tests results

scripts/system-tests/generate-properties-master.sh
When passing a custom Git repository URL to a systems-test job, the
master job doesn't pass this URL to the kernel and modules building job.
This makes the job fail when it can't checkout the desired commit on the
default remote.
To fix this, pass the URL received in the job parameter to the kernel
and modules building job.
=> Fix: jjb: system-tests: pass modules repo to build job

jobs/lttng-tools.yaml, scripts/lttng-tools/gerrit-build-override.sh, scripts/lttng-tools/gerrit-depends-on.sh, scripts/lttng-tools/gerrit-install-deps.sh
The development of a lttng-tools feature can happen in parallel with a
lttng-ust feature. The need to build and test a lttng-tools gerrit
change against a gerrit lttng-ust change arises.
This patch introduce gerrit-based inter project dependency
testing for the lttng-tools project against lttng-ust.
The dependency can be expressed at the change's commit message level:
Depends-on: lttng-ust: <lttng-ust-change-id>
e.g
Fix: client_flush_outgoing_queue expect an active client
Move validated and active assignation before the call to
client_flush_outgoing_queue.
Depends-on: lttng-ust: If8557b77f2a03b05b924cdc26ecf7618fff46289
Change-Id: I873b2fad567eb6d59a53a12cba02451afd1d9827
For now, only lttng-ust is supported but …
=> Introduce Depends-on for lttng-tools gerrit job

jobs/system-tests.yaml, scripts/system-tests/system-trigger.groovy
This release is no longer supported.
=> jjb: system-tests: remove LTTng stable-2.9 tests

jobs/lttng-tools.yaml, scripts/lttng-tools/gerrit-depends-on.sh
While there we can remove some conditional actions based on `conf`
"static" and "debug_rcu", since they are not defined for the gerrit job. It
facilitate the condition handling for `depends-on` handling.
Babeltrace is now always pulled and does not depends on any "$conf"
conditional action.
Since that for the remaining `conf` ("std", "agents", "no-ust") userspace_rcu is
required, use conditional only to handle the `Depends-on` feature.
=> jjb: Add "Depends-on: userspace-rcu:" for lttng-tools
