lttng/lttng-ci

jobs/lttng-baremetal-tests.yaml
lava/baremetal-tests/destructive-tests.yml
lava/baremetal-tests/failing-close.yml
lava/baremetal-tests/failing-open-efault.yml
lava/baremetal-tests/failing-open-enoent.yml
lava/baremetal-tests/perf-tests.yml
scripts/lttng-baremetal-tests/lava-submit.py
scripts/lttng-baremetal-tests/parse-results.py
scripts/lttng-baremetal-tests/run-baremetal-benchmarks.sh
scripts/lttng-baremetal-tests/run-baremetal-tests.sh
scripts/lttng-baremetal-tests/run-kvm-tests.sh

- Split KVM and baremetal lava test definitions
- Adds destructive and perf regression tests.
- Adds coverage of Linux mainline at every RC tag.
- Various bug fixes and improvements

Add test runs and improve kernel coverage

---

jobs/lttng-baremetal-tests.yaml
scripts/lttng-baremetal-tests/lava-submit.py
scripts/lttng-baremetal-tests/run-baremetal-benchmarks.sh
scripts/lttng-baremetal-tests/run-baremetal-tests.sh
scripts/lttng-baremetal-tests/run-kvm-tests.sh

-Change lava submission script to Python3
-Post IRC notification on test failure

Save and plot baremetal benchmark results

---

jobs/lttng-baremetal-tests.yaml

Lava: Rename vm jobs to be more generic

---

jobs/lttng-baremetal-tests.yaml
scripts/lttng-baremetal-tests/generate-plots.py
scripts/lttng-baremetal-tests/lava-submit.py
scripts/lttng-baremetal-tests/parse-results.py
scripts/lttng-baremetal-tests/summarize-results.sh

-Clean workspace on job completion
-Rework the way the metrics are computed
-Make canary jobs run once a day

Add plot generating scripts

---

scripts/lttng-baremetal-tests/generate-plots.py

jjb: Set the X axis to a finer granularity for benchmark plots

---

jobs/lttng-baremetal-tests.yaml
scripts/lttng-baremetal-tests/generate-properties-master.sh
scripts/lttng-baremetal-tests/inject-ssh-commands.sh

jjb: Add ssh command in injection build step for benchmark jobs

---

jobs/lttng-baremetal-tests.yaml
lava/baremetal-tests/success-dup-close.yml
scripts/lttng-baremetal-tests/generate-properties-slave.sh
scripts/lttng-baremetal-tests/lava-submit.py
scripts/lttng-baremetal-tests/parse-results.py
scripts/lttng-baremetal-tests/run-baremetal-benchmarks.sh

Also, remove unused metric and change add a parameter in kernel building job for more flexible testing.

Replace of enoent testcase because of high variance in results

---

scripts/lttng-baremetal-tests/run-baremetal-benchmarks.sh
scripts/lttng-baremetal-tests/run-baremetal-tests.sh
scripts/lttng-baremetal-tests/run-kvm-tests.sh
scripts/lttng-baremetal-tests/summarize-results.sh

Also use the LTTNG_CI_PATH variable to checkout the lttng-ci repo.

Add timestamp to benchmark metadata.

---

jobs/lttng-baremetal-tests.yaml
scripts/lttng-baremetal-tests/kprobe-fuzzing.sh
scripts/lttng-baremetal-tests/lava-submit.py
scripts/lttng-baremetal-tests/run-kvm-fuzzing-tests.sh

Also, update timeouts to smaller values.

Move kprobe fuzzing lava test to its own lava job.

---

scripts/lttng-baremetal-tests/lava-submit.py

jjb: lava: increase timeout time for vm tests

---

README.md

Use upstream jjb instead of custom from mjeanson

---

jobs/lttng-baremetal-tests.yaml
scripts/lttng-baremetal-tests/lava-submit.py

and bubble up fault rather than silencing it

Make mainline jobs track LTTng master branches

---

jobs/ctf-java.yml
jobs/jabberwocky.yml
jobs/libdelorean-java.yml
jobs/lttng-scope.yml

Based on the workflow of their maintainer these jobs should be run daily.

Build certain jobs daily

---

jobs/lttng-ivc.yaml
scripts/lttng-ivc/build.sh

Heavily inspired from lttng-analyses job definition.

Introduce lttng-ivc jobs

---

scripts/system-tests/run-baremetal-benchmarks.sh
scripts/system-tests/run-baremetal-tests.sh
scripts/system-tests/run-kvm-fuzzing-tests.sh
scripts/system-tests/run-kvm-tests.sh
scripts/system-tests/summarize-results.sh

jjb: lava: fix: update path to scripts

---

lava/system-tests/destructive-tests.yml
lava/system-tests/kernel-tests.yml
lava/system-tests/kprobe-fuzzing-tests.yml
lava/system-tests/perf-tests.yml

jjb: lava: Fix: lava jobs attaching files to wrong test case

---

lava/system-tests/kprobe-fuzzing-generate-data.yml

jjb: lava: kprobe-fuzzing: Fix syntax error in test definition

---

jobs/system-tests.yaml

jjb: systems-tests: include executed test suites in job description

---

jobs/ctf-java.yml
jobs/jabberwocky.yml
jobs/libdelorean-java.yml
jobs/lttng-scope.yml
jobs/lttng-ust-java-tests.yaml

Replace alexmonthy email notification to new maintainer

---

scripts/lttng-tools/hang_processes.sh

See individual commit messages for details.

Some small cleanups

---

scripts/lttng-tools/hang_processes.sh

While this is quite ugly, it has the advantage that we get the path to
the object files actually loaded by the application.  So if it loaded
some particular shared object due due to some LD_LIBRARY_PATH value or
because it dlopen'ed them, we will catch them.
Signed-off-by: Simon Marchi <simon.marchi@efficios.com>

hang_processes.sh: Obtain list of loaded dynamic objects using strings

---

scripts/system-tests/lava2-submit.py
scripts/system-tests/run-baremetal-benchmarks.sh
scripts/system-tests/run-baremetal-tests.sh
scripts/system-tests/run-kvm-fuzzing-tests.sh
scripts/system-tests/run-kvm-tests.sh

jjb: system-tests: add parameters for Tools and UST git repos

---

scripts/system-tests/lava2-submit.py

Cleanup: system-tests: format lava2-submit.py according to `black`

---

scripts/system-tests/lava2-submit.py

See follow commit for details:
commit be7f51b658568ac8d4d83aaf55b6ee381a75e04f
Author: Francis Deslauriers <francis.deslauriers@efficios.com>
Date:   Thu Dec 19 23:35:39 2019 -0500
jjb: system-tests: use `yaml.unsafe_load()` method

jjb: system-tests: replace remaining `yaml.load()` method

---

jobs/normand.yaml
scripts/normand/build.sh

I don't really know what I'm doing here.
I mostly copied `jobs/barectf.yaml` and `scripts/barectf/build.sh`.
Tell me if this looks okay.

jjb: add Normand job
